-- CreateTable
CREATE TABLE IF NOT EXISTS "tax_settings" (
  "id" TEXT NOT NULL,
  "company_id" TEXT NOT NULL DEFAULT 'default',
  "regime" TEXT NOT NULL DEFAULT 'SIMPLES_NACIONAL',
  "simples_anexo" TEXT DEFAULT 'III',
  "simples_aliquota_nominal" DECIMAL(5,4) DEFAULT 0.06,
  "simples_fator_reducao" DECIMAL(5,4) DEFAULT 0.00,
  "iss_aliquota" DECIMAL(5,4) DEFAULT 0.05,
  "iss_municipio" TEXT DEFAULT '',
  "iss_codigo_servico" TEXT DEFAULT '7.09',
  "irpj_percentual_presuncao" DECIMAL(5,4) DEFAULT 0.08,
  "irpj_aliquota" DECIMAL(5,4) DEFAULT 0.15,
  "irpj_adicional_aliquota" DECIMAL(5,4) DEFAULT 0.10,
  "irpj_adicional_limite_mensal" DECIMAL(15,2) DEFAULT 20000.00,
  "csll_percentual_presuncao" DECIMAL(5,4) DEFAULT 0.12,
  "csll_aliquota" DECIMAL(5,4) DEFAULT 0.09,
  "pis_regime" TEXT DEFAULT 'CUMULATIVO',
  "pis_aliquota" DECIMAL(5,4) DEFAULT 0.0065,
  "cofins_regime" TEXT DEFAULT 'CUMULATIVO',
  "cofins_aliquota" DECIMAL(5,4) DEFAULT 0.03,
  "inss_aliquota_patronal" DECIMAL(5,4) DEFAULT 0.20,
  "inss_rat_aliquota" DECIMAL(5,4) DEFAULT 0.03,
  "inss_fap" DECIMAL(5,4) DEFAULT 1.00,
  "inss_terceiros_aliquota" DECIMAL(5,4) DEFAULT 0.058,
  "fgts_aliquota" DECIMAL(5,4) DEFAULT 0.08,
  "ativo" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "tax_settings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "tax_apurations" (
  "id" TEXT NOT NULL,
  "competencia" TEXT NOT NULL,
  "regime" TEXT NOT NULL,
  "faturamento_bruto" DECIMAL(15,2) NOT NULL DEFAULT 0,
  "deducoes" DECIMAL(15,2) NOT NULL DEFAULT 0,
  "faturamento_liquido" DECIMAL(15,2) NOT NULL DEFAULT 0,
  "folha_pagamento" DECIMAL(15,2) NOT NULL DEFAULT 0,
  "simples_receita_bruta_12m" DECIMAL(15,2) DEFAULT 0,
  "simples_aliquota_efetiva" DECIMAL(7,6) DEFAULT 0,
  "simples_valor" DECIMAL(15,2) DEFAULT 0,
  "simples_vencimento" DATE,
  "simples_pago" BOOLEAN DEFAULT false,
  "simples_data_pagamento" DATE,
  "iss_base" DECIMAL(15,2) DEFAULT 0,
  "iss_valor" DECIMAL(15,2) DEFAULT 0,
  "iss_vencimento" DATE,
  "iss_pago" BOOLEAN DEFAULT false,
  "iss_data_pagamento" DATE,
  "irpj_base" DECIMAL(15,2) DEFAULT 0,
  "irpj_valor" DECIMAL(15,2) DEFAULT 0,
  "irpj_adicional" DECIMAL(15,2) DEFAULT 0,
  "irpj_total" DECIMAL(15,2) DEFAULT 0,
  "irpj_vencimento" DATE,
  "irpj_pago" BOOLEAN DEFAULT false,
  "irpj_data_pagamento" DATE,
  "csll_base" DECIMAL(15,2) DEFAULT 0,
  "csll_valor" DECIMAL(15,2) DEFAULT 0,
  "csll_vencimento" DATE,
  "csll_pago" BOOLEAN DEFAULT false,
  "csll_data_pagamento" DATE,
  "pis_base" DECIMAL(15,2) DEFAULT 0,
  "pis_valor" DECIMAL(15,2) DEFAULT 0,
  "pis_vencimento" DATE,
  "pis_pago" BOOLEAN DEFAULT false,
  "pis_data_pagamento" DATE,
  "cofins_base" DECIMAL(15,2) DEFAULT 0,
  "cofins_valor" DECIMAL(15,2) DEFAULT 0,
  "cofins_vencimento" DATE,
  "cofins_pago" BOOLEAN DEFAULT false,
  "cofins_data_pagamento" DATE,
  "inss_base_folha" DECIMAL(15,2) DEFAULT 0,
  "inss_patronal_valor" DECIMAL(15,2) DEFAULT 0,
  "inss_rat_valor" DECIMAL(15,2) DEFAULT 0,
  "inss_terceiros_valor" DECIMAL(15,2) DEFAULT 0,
  "inss_total" DECIMAL(15,2) DEFAULT 0,
  "inss_vencimento" DATE,
  "inss_pago" BOOLEAN DEFAULT false,
  "inss_data_pagamento" DATE,
  "fgts_base" DECIMAL(15,2) DEFAULT 0,
  "fgts_valor" DECIMAL(15,2) DEFAULT 0,
  "fgts_vencimento" DATE,
  "fgts_pago" BOOLEAN DEFAULT false,
  "fgts_data_pagamento" DATE,
  "total_impostos" DECIMAL(15,2) NOT NULL DEFAULT 0,
  "total_pago" DECIMAL(15,2) NOT NULL DEFAULT 0,
  "total_pendente" DECIMAL(15,2) NOT NULL DEFAULT 0,
  "observacoes" TEXT,
  "status" TEXT NOT NULL DEFAULT 'RASCUNHO',
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "tax_apurations_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "tax_apurations_competencia_key" UNIQUE ("competencia")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "tax_payments" (
  "id" TEXT NOT NULL,
  "apuration_id" TEXT,
  "competencia" TEXT NOT NULL,
  "tributo" TEXT NOT NULL,
  "descricao" TEXT NOT NULL,
  "valor" DECIMAL(15,2) NOT NULL,
  "vencimento" DATE NOT NULL,
  "data_pagamento" DATE,
  "status" TEXT NOT NULL DEFAULT 'PENDENTE',
  "numero_guia" TEXT,
  "banco" TEXT,
  "observacoes" TEXT,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "tax_payments_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "tax_payments_apuration_fkey" FOREIGN KEY ("apuration_id") REFERENCES "tax_apurations"("id") ON DELETE SET NULL
);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "tax_apurations_competencia_idx" ON "tax_apurations"("competencia");
CREATE INDEX IF NOT EXISTS "tax_payments_competencia_idx" ON "tax_payments"("competencia");
CREATE INDEX IF NOT EXISTS "tax_payments_status_idx" ON "tax_payments"("status");
CREATE INDEX IF NOT EXISTS "tax_payments_vencimento_idx" ON "tax_payments"("vencimento");
